version: '3'

services:
  root:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app

  app1:
    build: 
      context: ./app1
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  # interaction-test:
  #   build: 
  #     context: ./app1
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app